
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yuktbdmlvuxwcmqpcsyk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1a3RiZG1sdnV4d2NtcXBjc3lrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1NTIwNDAsImV4cCI6MjA1OTEyODA0MH0.-xNjyNwWI9Grv6C6rGqIzShvFZV9IcKQVwMOnDklWQo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Add cart operations as direct functions to avoid type issues
export const deleteCartItems = async (userId: string) => {
  return await supabase.rpc('delete_cart_items', { user_id_param: userId });
};

export const addCartItem = async (userId: string, productId: string, quantity: number, size: string, color: string) => {
  return await supabase.rpc('add_cart_item', { 
    user_id_param: userId, 
    product_id_param: productId, 
    quantity_param: quantity, 
    size_param: size, 
    color_param: color 
  });
};

export const getCartWithProducts = async (userId: string) => {
  return await supabase.rpc('get_cart_with_products', { user_id_param: userId });
};
